<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { reportsApi } from '../api/services'
import AppLoading from '../components/AppLoading.vue'
import AppNotice from '../components/AppNotice.vue'
import type { SummaryReport } from '../types/api'
import { ApiError } from '../api/http'
const report = ref<SummaryReport | null>(null), loading = ref(true), error = ref('')
const money = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' })
onMounted(async () => { try { report.value = await reportsApi.summary() } catch (e) { error.value = e instanceof ApiError ? e.message : 'Não foi possível carregar o dashboard.' } finally { loading.value = false } })
</script>
<template><section class="page"><div class="page-heading"><div><p class="eyebrow">VISÃO EXECUTIVA</p><h1>Dashboard</h1><p>Indicadores consolidados de estratégia, execução e retorno.</p></div></div><AppNotice tone="error" :message="error"/><AppLoading v-if="loading"/><template v-else-if="report"><section class="metric-grid"><article class="metric"><span>Estratégias</span><strong>{{ report.totalStrategies }}</strong><small>{{ report.activeStrategies }} vigentes</small></article><article class="metric"><span>Ideias</span><strong>{{ report.totalIdeas }}</strong><small>{{ report.totalProjects }} projetos</small></article><article class="metric"><span>Investimento planejado</span><strong>{{ money.format(report.plannedInvestment) }}</strong><small>Realizado: {{ money.format(report.actualInvestment) }}</small></article><article class="metric"><span>Benefício líquido realizado</span><strong>{{ money.format(report.actualNetBenefit) }}</strong><small>ROI: {{ report.actualRoiAvailable ? `${report.actualRoi}%` : 'indisponível' }}</small></article></section><section class="dashboard-grid"><article class="panel"><h2>Ideias por status</h2><dl><template v-for="(value, key) in report.ideasByStatus" :key="key"><dt>{{ key }}</dt><dd>{{ value }}</dd></template></dl><h2>Projetos por estágio</h2><dl><template v-for="(value, key) in report.projectsByStage" :key="key"><dt>{{ key }}</dt><dd>{{ value }}</dd></template></dl></article><article class="panel"><h2>Retorno financeiro</h2><dl><dt>Benefício previsto</dt><dd>{{ money.format(report.forecastFinancialBenefit) }}</dd><dt>Benefício realizado</dt><dd>{{ money.format(report.actualFinancialBenefit) }}</dd><dt>ROI previsto</dt><dd>{{ report.forecastRoiAvailable ? `${report.forecastRoi}%` : 'Indisponível' }}</dd><dt>ROI realizado</dt><dd>{{ report.actualRoiAvailable ? `${report.actualRoi}%` : 'Indisponível' }}</dd></dl></article></section><section class="panel"><h2>Desempenho por estratégia</h2><div class="table-wrap"><table><thead><tr><th>Estratégia</th><th>Ideias</th><th>Projetos</th><th>Investimento realizado</th><th>Benefício líquido</th><th>ROI</th></tr></thead><tbody><tr v-for="strategy in report.strategies" :key="strategy.strategyId"><td>{{ strategy.strategyTitle }}<small>{{ strategy.category }} · {{ strategy.campaign }}</small></td><td>{{ strategy.ideaCount }}</td><td>{{ strategy.projectCount }}</td><td>{{ money.format(strategy.actualInvestment) }}</td><td>{{ money.format(strategy.actualNetBenefit) }}</td><td>{{ strategy.actualRoiAvailable ? `${strategy.actualRoi}%` : '—' }}</td></tr></tbody></table></div></section></template></section></template>
