<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { strategiesApi } from '../api/services'
import { ApiError } from '../api/http'
import AppLoading from '../components/AppLoading.vue'; import AppNotice from '../components/AppNotice.vue'; import { useAuth } from '../composables/useAuth'
import type { Strategy } from '../types/api'
const rows = ref<Strategy[]>([]), loading = ref(true), error = ref(''), success = ref(''), showForm = ref(false), editing = ref<Strategy | null>(null)
const form = ref({ title: '', description: '', category: '', campaign: '', startsOn: '', endsOn: '' }); const etag = ref(''); const router = useRouter(); const { state } = useAuth()
async function load() { loading.value = true; error.value = ''; try { rows.value = (await strategiesApi.list()).content } catch (e) { error.value = e instanceof ApiError ? e.message : 'Falha ao carregar estratégias.' } finally { loading.value = false } }
function openCreate() { editing.value = null; form.value = { title: '', description: '', category: '', campaign: '', startsOn: '', endsOn: '' }; showForm.value = true }
async function openEdit(item: Strategy) { try { const result = await strategiesApi.get(item.id); editing.value = result.data; etag.value = result.etag || ''; form.value = { title: item.title, description: item.description, category: item.category, campaign: item.campaign, startsOn: item.startsOn, endsOn: item.endsOn }; showForm.value = true } catch (e) { error.value = e instanceof ApiError ? e.message : 'Falha ao abrir estratégia.' } }
async function save() { try { if (editing.value) await strategiesApi.update(editing.value.id, form.value, etag.value); else await strategiesApi.create(form.value); success.value = editing.value ? 'Estratégia atualizada.' : 'Estratégia criada.'; showForm.value = false; await load() } catch (e) { error.value = e instanceof ApiError ? e.message : 'Não foi possível salvar.' } }
async function archive(item: Strategy) { if (!confirm(`Arquivar “${item.title}”?`)) return; try { const result = await strategiesApi.get(item.id); await strategiesApi.archive(item.id, result.etag || ''); success.value = 'Estratégia arquivada.'; await load() } catch (e) { error.value = e instanceof ApiError ? e.message : 'Não foi possível arquivar.' } }
async function history(item: Strategy) { router.push({ name: 'strategy-history', params: { id: item.id } }) }
onMounted(load)
</script>
<template><section class="page"><div class="page-heading"><div><p class="eyebrow">DIRECIONAMENTO</p><h1>Estratégias</h1><p>Campanhas e prioridades que orientam as iniciativas.</p></div><button v-if="state.user?.role === 'LEADER'" class="button button--primary" @click="openCreate">Nova estratégia</button></div><AppNotice tone="error" :message="error"/><AppNotice tone="success" :message="success"/><AppLoading v-if="loading"/><div v-else-if="!rows.length" class="empty"><h2>Nenhuma estratégia disponível</h2><p>Crie uma estratégia vigente para receber ideias.</p></div><div v-else class="table-wrap"><table><thead><tr><th>Estratégia</th><th>Categoria</th><th>Campanha</th><th>Vigência</th><th>Situação</th><th></th></tr></thead><tbody><tr v-for="item in rows" :key="item.id"><td><strong>{{ item.title }}</strong><small>{{ item.description }}</small></td><td>{{ item.category }}</td><td>{{ item.campaign }}</td><td>{{ item.startsOn }} — {{ item.endsOn }}</td><td><span class="badge" :class="item.active ? 'badge--success' : 'badge--muted'">{{ item.archived ? 'Arquivada' : item.active ? 'Vigente' : 'Fora da vigência' }}</span></td><td class="actions"><button class="text-button" @click="history(item)">Histórico</button><button v-if="state.user?.role === 'LEADER'" class="text-button" @click="openEdit(item)">Editar</button><button v-if="state.user?.role === 'LEADER' && !item.archived" class="text-button text-button--danger" @click="archive(item)">Arquivar</button></td></tr></tbody></table></div><div v-if="showForm" class="modal"><form class="dialog" @submit.prevent="save"><h2>{{ editing ? 'Editar estratégia' : 'Nova estratégia' }}</h2><label>Título<input v-model="form.title" required></label><label>Descrição<textarea v-model="form.description" required></textarea></label><div class="form-grid"><label>Categoria<input v-model="form.category" required></label><label>Campanha<input v-model="form.campaign" required></label><label>Início<input v-model="form.startsOn" type="date" required></label><label>Fim<input v-model="form.endsOn" type="date" required></label></div><div class="dialog-actions"><button type="button" class="button" @click="showForm = false">Cancelar</button><button class="button button--primary">Salvar</button></div></form></div></section></template>
